### ISSUE TITLE
Review Project Requirements

### ISSUE THREAD

**Issue by cancelei** [cancelei/recipe-in-rails#19]
Project link> https://github.com/users/cancelei/projects/6

 Now the link is not Private.

We're a team of 2 people

**Comment by topeogunleye** [comment]
Hello @cancelei, I am your Code Reviewer,

Please kindly provide a valid project link and also include information about the number of people in your group

**Comment by topeogunleye** [comment]
Hi @cancelei, @Javivy 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that doesn't have a valid project link and also includes information about the number of people in your group

<img width="774" alt="image" src="https://github.com/cancelei/recipe-in-rails/assets/52934128/61979f65-494c-4b6e-9293-dfa021a29773">

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

**Comment by thecodechaser** [comment]
## STATUS: APPROVED 🟢

## Hi @cancelei, and @Javivy👋, 

Your project is complete!  There is nothing else to say other than... it's time to close it :shipit: 
Congratulations! 🎉 

<img src="https://media3.giphy.com/media/g9582DNuQppxC/giphy-downsized-medium.gif"/>

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
